// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApi.Data;

#nullable disable

namespace MinimalApi.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20240622095323_ManyToManyBasics6")]
    partial class ManyToManyBasics6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MinimalApi.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 60.0m,
                            ReleaseDate = new DateOnly(2012, 8, 25),
                            Title = "Hitman: Absolution"
                        },
                        new
                        {
                            Id = 2,
                            Price = 50.0m,
                            ReleaseDate = new DateOnly(2015, 5, 19),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 3,
                            Price = 70.0m,
                            ReleaseDate = new DateOnly(2018, 10, 26),
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 4,
                            Price = 30.0m,
                            ReleaseDate = new DateOnly(2013, 9, 17),
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 5,
                            Price = 50.0m,
                            ReleaseDate = new DateOnly(2018, 10, 5),
                            Title = "Assassin's Creed Odyssey"
                        },
                        new
                        {
                            Id = 6,
                            Price = 60.0m,
                            ReleaseDate = new DateOnly(2020, 12, 10),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 7,
                            Price = 40.0m,
                            ReleaseDate = new DateOnly(2016, 4, 12),
                            Title = "Dark Souls III"
                        },
                        new
                        {
                            Id = 8,
                            Price = 60.0m,
                            ReleaseDate = new DateOnly(2021, 5, 7),
                            Title = "Resident Evil Village"
                        },
                        new
                        {
                            Id = 9,
                            Price = 60.0m,
                            ReleaseDate = new DateOnly(2022, 2, 25),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 10,
                            Price = 40.0m,
                            ReleaseDate = new DateOnly(2017, 2, 28),
                            Title = "Horizon Zero Dawn"
                        },
                        new
                        {
                            Id = 11,
                            Price = 40.0m,
                            ReleaseDate = new DateOnly(2018, 4, 20),
                            Title = "God of War"
                        });
                });

            modelBuilder.Entity("MinimalApi.Entities.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 14
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 17
                        });
                });

            modelBuilder.Entity("MinimalApi.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Role-Playing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Educational"
                        },
                        new
                        {
                            Id = 16,
                            Name = "MMO"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Visual Novel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tactical"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Survival"
                        });
                });

            modelBuilder.Entity("MinimalApi.Entities.GameGenre", b =>
                {
                    b.HasOne("MinimalApi.Entities.Game", null)
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalApi.Entities.Genre", null)
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalApi.Entities.Game", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("MinimalApi.Entities.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
