### Get all games.
GET http://localhost:5053/games/

### Get a game with a specified Id.
GET http://localhost:5053/games/15

### Try to get a game that does not exist.
GET http://localhost:5053/games/100

### Create a new game.
POST http://localhost:5053/games/
Content-Type: application/json

{
    "title": "Medal of Honor: Above and Beyond",
    "genres": [1, 13],
    "price": "39.99",
    "releaseDate": "2020-12-10"
}

### Update a game with a given Id.
PUT http://localhost:5053/games/15
Content-Type: application/json

{
    "title": "Genshin Impact",
    "genres": [1,5],
    "price": "0.00"
}

### Given an Id delete a game.
DELETE http://localhost:5053/games/13